### PR TITLE
1-D vector stored with cluster id

### PR DESCRIPTION
**Pull request by subhojit-mukherjee**
As per conversation with Michael, we understood that we need 1-D vector representation for every cluster id. This code block serves the same.

### CODE REVIEW

**Comment by subhojit-mukherjee** [comment]
@durandom Could you verify this and merge?

**Comment by MichaelClifford** [comment]
@subhojit-mukherjee LGTM.

**Comment by subhojit-mukherjee** [comment]
> LGTM.

image
:)

**Review by durandom — APPROVED** [review]
@subhojit-mukherjee generally you should try to keep your methods small. The `on_next` already contains way too much logic. Try to refactor it into smaller methods.

**Pull request merged**
