### PR TITLE
Update .zuul.yaml

### PR DESCRIPTION
**Pull request by 4n4nd**
Add build trigger for the staging env

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
LGTM :+1: , Dont forget to reference secret in buildconfig.

**Comment by harshad16** [comment]
> Build failed.
> 
> * [thoth-coala ](https://managesf.thoth-station.ninja/logs/03/103/24f790615f9d819052d3bc234d3426b6e657e881/check/thoth-coala/d611b33/) : FAILURE in 44s
> * [thoth-pytest ](https://managesf.thoth-station.ninja/logs/03/103/24f790615f9d819052d3bc234d3426b6e657e881/check/thoth-pytest/d4604cb/) : FAILURE in 1m 32s

@4n4nd PTAL

**Comment by 4n4nd** [comment]
> > Build failed.
> > 
> > * [thoth-coala ](https://managesf.thoth-station.ninja/logs/03/103/24f790615f9d819052d3bc234d3426b6e657e881/check/thoth-coala/d611b33/) : FAILURE in 44s
> > * [thoth-pytest ](https://managesf.thoth-station.ninja/logs/03/103/24f790615f9d819052d3bc234d3426b6e657e881/check/thoth-pytest/d4604cb/) : FAILURE in 1m 32s
> 
> @4n4nd PTAL

:( That's old files

**Review by HumairAK — APPROVED** [review]

**Comment by harshad16** [comment]
Fixes: #101

**Pull request merged**
