### PR TITLE
initial take on the flatliners

### PR DESCRIPTION
**Pull request by durandom**
Layout foundation for stream processing of metrics.

Implemented via [ReactiveX](https://github.com/ReactiveX/RxPY)

### CODE REVIEW

**Comment by durandom** [comment]
@fridex could you do a python style review? 
I'm still not sure how to properly name things and do this import stuff.
And you can be pedantic 😄 I guess there will be a lot of cut'n'paste going on in this repo....

**Review by fridex — APPROVED** [review]
Nothing bad spotted in pedantic mode 🙂. I have a feeling you like object oriented programming.

Btw linters will argue when variable name is "file".

**Comment by goern** [comment]
ah btw, shall we send some bots in to help you keep things up to date... and maybe some linting?!

**Comment by durandom** [comment]
Thanks @fridex 

>  I have a feeling you like object oriented programming

well, if it fits the job. Would there be a more pythonic way to do this? 
I've once tried [composition](https://robots.thoughtbot.com/reusable-oo-composition-vs-inheritance), because thats heavily used in ruby, but that did not work well in python. Maybe I was doing it wrong

**Pull request merged**
